import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { openModal } from '@w3vm/web3modal'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <w3m-button/>
        <button onClick={openModal} >Open</button>
      </main>
    </>
  )
}
